# Generated by Django 5.1.15 on 2026-06-26 07:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='files_audit_user_id_bba6a4_idx',
            old_name='files_audit_user_i_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='files_audit_action_657751_idx',
            old_name='files_audit_action_idx',
        ),
        migrations.RenameIndex(
            model_name='filerecord',
            new_name='files_filer_owner_i_875311_idx',
            old_name='files_filer_owner_i_idx',
        ),
        migrations.RenameIndex(
            model_name='filerecord',
            new_name='files_filer_owner_i_204dbd_idx',
            old_name='files_filer_owner_n_idx',
        ),
        migrations.AddField(
            model_name='folder',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='files.folder'),
        ),
        migrations.AddField(
            model_name='filerecord',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='files.folder'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['owner', 'parent'], name='files_folde_owner_i_385c7c_idx'),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(fields=('owner', 'parent', 'name'), name='unique_folder_name_per_parent'),
        ),
    ]
